/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugfe_ıvecek_1621231018_bpıı_odev2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tuğfe
 */
public class KullaniciGiris extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciGiris
     */
    DefaultListModel dlm = new DefaultListModel();
    
    public KullaniciGiris() {
        initComponents();
        setTitle("Kullanıcı Giriş Ekranı");
        
        listYayınevleri.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGiris = new javax.swing.JPanel();
        lblSifre = new javax.swing.JLabel();
        lblKullaniciaAdi = new javax.swing.JLabel();
        txtKullaniciAdi = new javax.swing.JTextField();
        txtSifre = new javax.swing.JTextField();
        btnGiris = new javax.swing.JButton();
        btnKullaniciEkle = new javax.swing.JButton();
        btnYayinEvleri = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblSifreDurum = new javax.swing.JLabel();
        lblKullaniciAdiDurum1 = new javax.swing.JLabel();
        PanelKulanıcıKayit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTcNumarasi = new javax.swing.JLabel();
        lblKullaniciAdi = new javax.swing.JLabel();
        lblSifreKullaniciEkle = new javax.swing.JLabel();
        lblAdi = new javax.swing.JLabel();
        lblSoyadi = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        txtTc = new javax.swing.JTextField();
        txtKullaniciAdiEkle = new javax.swing.JTextField();
        txtSifreEkle = new javax.swing.JTextField();
        txtAdiEkle = new javax.swing.JTextField();
        txtSoyadiEkle = new javax.swing.JTextField();
        txtMailEkle = new javax.swing.JTextField();
        btnKaydet = new javax.swing.JButton();
        btnTemizle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnGeri = new javax.swing.JButton();
        lblSifreKontrol = new javax.swing.JLabel();
        lblTcKontrol = new javax.swing.JLabel();
        lblKullaniciAdiKontrol = new javax.swing.JLabel();
        lblSoyadiKontrol = new javax.swing.JLabel();
        lblMailKontrol = new javax.swing.JLabel();
        lblAdiKontrol = new javax.swing.JLabel();
        PanelYayınEvi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblYayinEviKodu = new javax.swing.JLabel();
        lblYayinEviAdi = new javax.swing.JLabel();
        lblYayinEviIl = new javax.swing.JLabel();
        lblYayinEviIlce = new javax.swing.JLabel();
        txtYayıneviKodu = new javax.swing.JTextField();
        txtYayıneviAdi = new javax.swing.JTextField();
        txtYayıneviIlce = new javax.swing.JTextField();
        txtYayıneviIl = new javax.swing.JTextField();
        btnYayıneviEkle = new javax.swing.JButton();
        btnYayıneviKaydet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listYayınevleri = new javax.swing.JList<>();
        btnGoruntule = new javax.swing.JButton();
        txtUyari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        lblSifre.setText("Şifre:");

        lblKullaniciaAdi.setText("Kullanıcı Adı:");

        txtKullaniciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKullaniciAdiActionPerformed(evt);
            }
        });

        btnGiris.setText("Giriş");
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });

        btnKullaniciEkle.setText("Kullanıcı Ekle");
        btnKullaniciEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciEkleActionPerformed(evt);
            }
        });

        btnYayinEvleri.setText("Yayınevleri");
        btnYayinEvleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYayinEvleriActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("KİTAP YAYINCILIĞI");

        javax.swing.GroupLayout PanelGirisLayout = new javax.swing.GroupLayout(PanelGiris);
        PanelGiris.setLayout(PanelGirisLayout);
        PanelGirisLayout.setHorizontalGroup(
            PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGirisLayout.createSequentialGroup()
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelGirisLayout.createSequentialGroup()
                                .addComponent(btnKullaniciEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnYayinEvleri, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelGirisLayout.createSequentialGroup()
                                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelGirisLayout.createSequentialGroup()
                                        .addComponent(lblKullaniciaAdi)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelGirisLayout.createSequentialGroup()
                                        .addComponent(lblSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblKullaniciAdiDurum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSifreDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(169, 169, 169))
        );
        PanelGirisLayout.setVerticalGroup(
            PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGirisLayout.createSequentialGroup()
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addContainerGap(62, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(btnGiris)
                        .addGap(52, 52, 52))
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblKullaniciaAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblKullaniciAdiDurum1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSifre))
                            .addComponent(lblSifreDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)))
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKullaniciEkle)
                    .addComponent(btnYayinEvleri))
                .addGap(55, 55, 55))
        );

        getContentPane().add(PanelGiris, "card12");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Kullanıcı Ekleme Ekranı");

        lblTcNumarasi.setText("Tc Numarasi :");

        lblKullaniciAdi.setText("Kullanici Adi :");

        lblSifreKullaniciEkle.setText("Şifre :");

        lblAdi.setText("Adı :");

        lblSoyadi.setText("Soyadı :");

        lblMail.setText("Mail :");

        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        btnTemizle.setText("Temizle");
        btnTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemizleActionPerformed(evt);
            }
        });

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnGeri.setText("Geri");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKulanıcıKayitLayout = new javax.swing.GroupLayout(PanelKulanıcıKayit);
        PanelKulanıcıKayit.setLayout(PanelKulanıcıKayitLayout);
        PanelKulanıcıKayitLayout.setHorizontalGroup(
            PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTcNumarasi)
                            .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblSoyadi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSifreKullaniciEkle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAdi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblKullaniciAdi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTc)
                            .addComponent(txtKullaniciAdiEkle)
                            .addComponent(txtSifreEkle)
                            .addComponent(txtAdiEkle)
                            .addComponent(txtSoyadiEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtMailEkle))
                        .addGap(47, 47, 47)
                        .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTemizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGeri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTcKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(lblSifreKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSoyadiKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAdiKontrol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMailKontrol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1)))
                .addGap(14, 14, 14))
            .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                    .addGap(472, 472, 472)
                    .addComponent(lblKullaniciAdiKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );
        PanelKulanıcıKayitLayout.setVerticalGroup(
            PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                                .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTcNumarasi)
                                    .addComponent(txtTc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblKullaniciAdi)
                                    .addComponent(txtKullaniciAdiEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSifreKullaniciEkle)
                                    .addComponent(txtSifreEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                                .addComponent(lblTcKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSifreKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnKaydet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTemizle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAdi)
                        .addComponent(txtAdiEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSil)
                    .addComponent(lblAdiKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnGeri))
                    .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                                .addComponent(lblSoyadiKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMailKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                                .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSoyadi)
                                    .addComponent(txtSoyadiEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMail)
                                    .addComponent(txtMailEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(PanelKulanıcıKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelKulanıcıKayitLayout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(lblKullaniciAdiKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(168, Short.MAX_VALUE)))
        );

        getContentPane().add(PanelKulanıcıKayit, "card3");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Yayınevi Ekleyiniz");

        lblYayinEviKodu.setText("Yayınevi Kodu :");

        lblYayinEviAdi.setText("Yayınevi Adı :");

        lblYayinEviIl.setText("Yayınevi İli :");

        lblYayinEviIlce.setText("Yayınevi İlçesi :");

        btnYayıneviEkle.setText("Geri");
        btnYayıneviEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYayıneviEkleActionPerformed(evt);
            }
        });

        btnYayıneviKaydet.setText("Kaydet");
        btnYayıneviKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYayıneviKaydetActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listYayınevleri);

        btnGoruntule.setText("Görüntüle");
        btnGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoruntuleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelYayınEviLayout = new javax.swing.GroupLayout(PanelYayınEvi);
        PanelYayınEvi.setLayout(PanelYayınEviLayout);
        PanelYayınEviLayout.setHorizontalGroup(
            PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelYayınEviLayout.createSequentialGroup()
                .addGroup(PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelYayınEviLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel3))
                    .addGroup(PanelYayınEviLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelYayınEviLayout.createSequentialGroup()
                                .addGroup(PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblYayinEviKodu)
                                    .addComponent(lblYayinEviIlce)
                                    .addComponent(lblYayinEviAdi)
                                    .addComponent(lblYayinEviIl))
                                .addGap(18, 18, 18)
                                .addGroup(PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtYayıneviKodu)
                                    .addComponent(txtYayıneviAdi)
                                    .addComponent(txtYayıneviIlce)
                                    .addComponent(txtYayıneviIl)
                                    .addGroup(PanelYayınEviLayout.createSequentialGroup()
                                        .addComponent(btnYayıneviKaydet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnYayıneviEkle))))
                            .addComponent(txtUyari))
                        .addGroup(PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelYayınEviLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(btnGoruntule))
                            .addGroup(PanelYayınEviLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelYayınEviLayout.setVerticalGroup(
            PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelYayınEviLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addGroup(PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelYayınEviLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYayinEviKodu)
                            .addComponent(txtYayıneviKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYayinEviAdi)
                            .addComponent(txtYayıneviAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYayinEviIlce)
                            .addComponent(txtYayıneviIlce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtYayıneviIl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYayinEviIl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelYayınEviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnYayıneviKaydet)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelYayınEviLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnYayıneviEkle))))
                    .addGroup(PanelYayınEviLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGoruntule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(txtUyari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        getContentPane().add(PanelYayınEvi, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKullaniciAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKullaniciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKullaniciAdiActionPerformed

    private void btnKullaniciEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciEkleActionPerformed
        // TODO add your handling code here:
        PanelGiris.setVisible(false);
        PanelKulanıcıKayit.setVisible(true);
        
    }//GEN-LAST:event_btnKullaniciEkleActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        // TODO add your handling code here:
        
        
        try {
            // TODO add your handling code here:
            Pattern kAdiGirisDesen = Pattern.compile("^[a-zA-Z]+$");
            Pattern sifreGirisDesen = Pattern.compile("[0-9]");
            Matcher kAdiGirisYakala = kAdiGirisDesen.matcher(txtKullaniciAdi.getText());
            Matcher sifreGirisYakala = sifreGirisDesen.matcher(txtSifre.getText());
            if (!kAdiGirisYakala.find()) {

                lblKullaniciAdiDurum1.setText("Yanlış Bilgi Girilmiştir.");

            } else {
                lblKullaniciAdiDurum1.setText("");
            }
            if (!sifreGirisYakala.find()) {

                lblSifreDurum.setText("Yanlış Bilgi Girilmiştir.");

            } else {
                lblSifreDurum.setText("");
            }

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/KitapTakim ","kitap","kitap");
            String sqlSorgu = "SELECT * FROM KULLANICILAR WHERE KULLANICIADI=?";
            PreparedStatement psSorgu = con.prepareStatement(sqlSorgu);
            psSorgu.setString(1,txtKullaniciAdi.getText());
            ResultSet rs = psSorgu.executeQuery();

            if (rs.next()) {

                String KULLANICIADI = rs.getString("KULLANICIADI");
                String SIFRE = String.valueOf(rs.getInt("SIFRE"));
                if (KULLANICIADI.equals(txtKullaniciAdi.getText()) && SIFRE.equals(txtSifre.getText())) {
                    YayınTakip yt = new YayınTakip();

                    yt.setVisible(true);
                    this.dispose();

                } else  {
                    JOptionPane.showMessageDialog(this, "Bilgiler Doğru Girilmemiştir..");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btnGirisActionPerformed

    private void btnTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizleActionPerformed
        // TODO add your handling code here:
        txtAdiEkle.setText("");
        txtMailEkle.setText("");
        txtKullaniciAdiEkle.setText("");
        txtSoyadiEkle.setText("");
        txtTc.setText("");
        txtSifreEkle.setText("");
        
        
    }//GEN-LAST:event_btnTemizleActionPerformed

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        // TODO add your handling code here:
        PanelGiris.setVisible(true);
        PanelKulanıcıKayit.setVisible(false);
    }//GEN-LAST:event_btnGeriActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        // TODO add your handling code here:
        Pattern tcDesen = Pattern.compile("[0-9]");
        Matcher tcYakala = tcDesen.matcher(txtTc.getText());
        if(!tcYakala.find()){
           lblTcKontrol.setText("Geçerli bir TC Numarası Giriniz.");
        }else {
           lblTcKontrol.setText("");
        }
        Pattern kAdiDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher kAdiYakala = kAdiDesen.matcher(txtKullaniciAdiEkle.getText());
        if(!kAdiYakala.find()){
           lblKullaniciAdiKontrol.setText("Geçerli bir Kullanıcı Adı Giriniz.");
        }else {
           lblKullaniciAdiKontrol.setText("");
        }
        Pattern sifreDesen = Pattern.compile("[0-9]");
        Matcher sifreYakala = sifreDesen.matcher(txtSifreEkle.getText());
        if(!sifreYakala.find()){
           lblSifreKontrol.setText("Geçerli bir Şifre Giriniz.");
        }else {
           lblSifreKontrol.setText("");
        }
        Pattern AdiDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher AdiYakala = AdiDesen.matcher(txtAdiEkle.getText());
        if(!AdiYakala.find()){
           lblAdiKontrol.setText("Geçerli bir Adı Giriniz.");
        }else {
           lblAdiKontrol.setText("");
        }
        Pattern soyadiDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher soyadiYakala = soyadiDesen.matcher(txtSoyadiEkle.getText());
        if(!soyadiYakala.find()){
           lblSoyadiKontrol.setText("Geçerli bir Soyadı Giriniz.");
        }else {
           lblSoyadiKontrol.setText("");
        }
        Pattern mailDesen = Pattern.compile("[a-zA-Z@]");
        Matcher mailYakala = mailDesen.matcher(txtMailEkle.getText());
        if(!mailYakala.find()){
           lblMailKontrol.setText("Geçerli bir Soyadı Giriniz.");
        }else {
           lblMailKontrol.setText("");
        }
        
        
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/KitapTakim ","kitap","kitap");
            String sorgu = "SELECT * FROM KULLANICILAR WHERE TC=?";
            PreparedStatement psSorgu = con.prepareStatement(sorgu);
            psSorgu.setInt(1, Integer.parseInt(txtTc.getText()));
            ResultSet rs = psSorgu.executeQuery();
            
            if(rs.next()){
                String sqlUpdate ="UPDATE kullanıcılar" +"SET KULLANICIADI=?,SIFRE=?,ADI=?,SOYADI=?,MAIL=?"+"WHERE TC=?";
                PreparedStatement  psUpdate = con.prepareStatement(sqlUpdate);
                psUpdate.setInt(1, Integer.parseInt(txtTc.getText()));
                psUpdate.setString(2, txtKullaniciAdiEkle.getText());
                psUpdate.setInt(3, Integer.parseInt(txtSifreEkle.getText()));
                psUpdate.setString(4, txtAdiEkle.getText());
                psUpdate.setString(5, txtSoyadiEkle.getText());
                psUpdate.setString(6, txtMailEkle.getText());
                
                psUpdate.executeUpdate();
            }else{
                String sqlInsert ="INSERT INTO KULLANICILAR" +"(TC,KULLANICIADI,SIFRE,ADI,SOYADI,MAIL)"
                        + "VALUES (?,?,?,?,?,?)";
                PreparedStatement  psInsert = con.prepareStatement(sqlInsert);
                psInsert.setInt(1, Integer.parseInt(txtTc.getText()));
                psInsert.setString(2, txtKullaniciAdiEkle.getText());
                psInsert.setInt(3, Integer.parseInt(txtSifreEkle.getText()));
                psInsert.setString(4, txtAdiEkle.getText());
                psInsert.setString(5, txtSoyadiEkle.getText());
                psInsert.setString(6, txtMailEkle.getText());
                
                psInsert.executeUpdate();
                
                txtTc.setText("");
                txtKullaniciAdiEkle.setText("");
                txtSifreEkle.setText("");
                txtAdiEkle.setText("");
                txtSoyadiEkle.setText("");
                txtMailEkle.setText("");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        // TODO add your handling code here:
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/KitapTakim ","kitap","kitap");
            String delete = "DELETE FROM kullanıcılar WHERE TC=?";
            PreparedStatement psDelete = con.prepareStatement(delete);
            psDelete.setInt(1, Integer.parseInt(txtTc.getText()));
            psDelete.executeUpdate();
            
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnYayinEvleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYayinEvleriActionPerformed
        // TODO add your handling code here:
        PanelGiris.setVisible(false);
        PanelYayınEvi.setVisible(true);
    }//GEN-LAST:event_btnYayinEvleriActionPerformed

    private void btnYayıneviEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYayıneviEkleActionPerformed
        // TODO add your handling code here:
        PanelGiris.setVisible(true);
        PanelYayınEvi.setVisible(false);
    }//GEN-LAST:event_btnYayıneviEkleActionPerformed

    private void btnYayıneviKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYayıneviKaydetActionPerformed
        // TODO add your handling code here:
        Pattern yayınEviKoduDesen = Pattern.compile("[0-9]");
        Matcher yayınEviKoduYakala = yayınEviKoduDesen.matcher(txtYayıneviKodu.getText());
        if (!yayınEviKoduYakala.find()) {

            txtUyari.setText("Geçerli Yayınevi Kodu Giriniz.");

        } else {
            txtUyari.setText("");
        }
        Pattern yayınEviAdiDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher yayınEviAdiYakala = yayınEviAdiDesen.matcher(txtYayıneviAdi.getText());
        if (!yayınEviAdiYakala.find()) {
            txtUyari.setText("Geçerli Yayınevi Adı Giriniz.");
        } else {
            txtUyari.setText("");
        }
        Pattern yayınEvIlceDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher yayınEvIlceYakala = yayınEvIlceDesen.matcher(txtYayıneviIlce.getText());
        if (!yayınEvIlceYakala.find()) {
            txtUyari.setText("Geçerli Yayınevi Ilce Giriniz.");
        } else {
            txtUyari.setText("");
        }
        Pattern yayınEvIlDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher yayınEvIlYakala = yayınEvIlDesen.matcher(txtYayıneviIl.getText());
        if (!yayınEvIlYakala.find()) {
            txtUyari.setText("Geçerli Yayınevi Il Giriniz.");
        } else {
            txtUyari.setText("");
        }
        
        
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/KitapTakim ","kitap","kitap");
            String sqlSorgu = "SELECT * FROM YAYINEVLERİ WHERE YAYINEVIKODU=?";
            PreparedStatement psSorgu = con.prepareStatement(sqlSorgu);
            psSorgu.setInt(1, Integer.parseInt(txtYayıneviKodu.getText()));
            ResultSet rs = psSorgu.executeQuery();

            if (rs.next()) {
                String sqlUpdate = "UPDATE YAYINEVLERİ" + "SET YAYINEVIADI=?,YAYINEVIILCE=?,YAYINEVIIL=?" + "WHERE YAYINEVIKODU=?";
                PreparedStatement psUpdate = con.prepareStatement(sqlUpdate);
                psUpdate.setInt(1, Integer.parseInt(txtYayıneviKodu.getText()));
                psUpdate.setString(2, txtYayıneviAdi.getText());
                psUpdate.setString(3, txtYayıneviIlce.getText());
                psUpdate.setString(4, txtYayıneviIl.getText());
                psUpdate.executeUpdate();
            } else {
                String sqlInsert = "INSERT INTO YAYINEVLERİ"
                        + " (YAYINEVIKODU,YAYINEVIADI,YAYINEVIILCE,YAYINEVIIL) "
                        + " VALUES (?,?,?,?)";
                PreparedStatement psInsert = con.prepareStatement(sqlInsert);

                psInsert.setInt(1, Integer.parseInt(txtYayıneviKodu.getText()));
                psInsert.setString(2, txtYayıneviAdi.getText());
                psInsert.setString(3, txtYayıneviIlce.getText());
                psInsert.setString(4, txtYayıneviIl.getText());
               
               
                psInsert.executeUpdate();

                txtYayıneviKodu.setText("");
                txtYayıneviIl.setText("");
                txtYayıneviIlce.setText("");
                txtYayıneviAdi.setText("");
               
                

            }
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnYayıneviKaydetActionPerformed

    private void btnGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoruntuleActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select y from Yayinevleri y");
        List<Yayinevleri> yayinevleri = q.getResultList();
        
        for (Yayinevleri y : yayinevleri) {
            dlm.addElement("Yayınevi Adı :" +y.getYayineviadi()+ " Yayınevi İlçesi :"+ y.getYayineviilce() + " Yayınevi İl :" + y.getYayineviil());
        }
        
    }//GEN-LAST:event_btnGoruntuleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGiris;
    private javax.swing.JPanel PanelKulanıcıKayit;
    private javax.swing.JPanel PanelYayınEvi;
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnGoruntule;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnKullaniciEkle;
    private javax.swing.JButton btnSil;
    private javax.swing.JButton btnTemizle;
    private javax.swing.JButton btnYayinEvleri;
    private javax.swing.JButton btnYayıneviEkle;
    private javax.swing.JButton btnYayıneviKaydet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdi;
    private javax.swing.JLabel lblAdiKontrol;
    private javax.swing.JLabel lblKullaniciAdi;
    private javax.swing.JLabel lblKullaniciAdiDurum1;
    private javax.swing.JLabel lblKullaniciAdiKontrol;
    private javax.swing.JLabel lblKullaniciaAdi;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMailKontrol;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JLabel lblSifreDurum;
    private javax.swing.JLabel lblSifreKontrol;
    private javax.swing.JLabel lblSifreKullaniciEkle;
    private javax.swing.JLabel lblSoyadi;
    private javax.swing.JLabel lblSoyadiKontrol;
    private javax.swing.JLabel lblTcKontrol;
    private javax.swing.JLabel lblTcNumarasi;
    private javax.swing.JLabel lblYayinEviAdi;
    private javax.swing.JLabel lblYayinEviIl;
    private javax.swing.JLabel lblYayinEviIlce;
    private javax.swing.JLabel lblYayinEviKodu;
    private javax.swing.JList<String> listYayınevleri;
    private javax.swing.JTextField txtAdiEkle;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JTextField txtKullaniciAdiEkle;
    private javax.swing.JTextField txtMailEkle;
    private javax.swing.JTextField txtSifre;
    private javax.swing.JTextField txtSifreEkle;
    private javax.swing.JTextField txtSoyadiEkle;
    private javax.swing.JTextField txtTc;
    private javax.swing.JTextField txtUyari;
    private javax.swing.JTextField txtYayıneviAdi;
    private javax.swing.JTextField txtYayıneviIl;
    private javax.swing.JTextField txtYayıneviIlce;
    private javax.swing.JTextField txtYayıneviKodu;
    // End of variables declaration//GEN-END:variables
}
