/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugfe_ıvecek_1621231018_bpıı_odev2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuğfe
 */
public class YayınTakip extends javax.swing.JFrame {

    /**
     * Creates new form YayınTakip
     */
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultListModel dlm = new DefaultListModel();
    DefaultListModel dlm2 = new DefaultListModel();
    DefaultListModel dlm3 = new DefaultListModel();
    DefaultTableModel dtm2 = new DefaultTableModel();

    public YayınTakip() {
        initComponents();
        setTitle("Kitap Yayıncılığı Takip");
        tblKitap.setModel(dtm);
        listKitaplar.setModel(dlm);
        listYayınevleri.setModel(dlm2);
        listToplam.setModel(dlm3);
        tblDosyaOkuma.setModel(dtm2);

        dtm.setColumnIdentifiers(new String[]{"ISBN", "KITAPISMI", "BASIMYILI", "SAYFASAYISI", "FIYAT", "YAYINEVI", "YAZAR"});
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kitaplar k ");
        List<Kitaplar> kitaplar = q.getResultList();
        dtm.setRowCount(0);
        for (Kitaplar k : kitaplar) {
            dtm.addRow(new Object[]{k.getIsbn(), k.getKitapismi(), k.getBasimyili(),
                k.getSayfasayisi(), k.getFiyat(), k.getYayinevi(), k.getYazar()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelYayinTakip = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKitap = new javax.swing.JTable();
        btnKitapEkle = new javax.swing.JButton();
        btnKitapSil = new javax.swing.JButton();
        btnKitapDegistir = new javax.swing.JButton();
        btnKitapSorgu = new javax.swing.JButton();
        btnDosyadanOku = new javax.swing.JButton();
        btnKitapYazdir = new javax.swing.JButton();
        btnKullaniciYazdir = new javax.swing.JButton();
        btnKitaplar = new javax.swing.JButton();
        btnKitapYazarlari = new javax.swing.JButton();
        btnKitapDurum = new javax.swing.JButton();
        btnKitapFiyatlari = new javax.swing.JButton();
        btnKullaniciDegistir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PanelKitapSil = new javax.swing.JPanel();
        lblIsbnNoBilgi = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        txtIsbnSil = new javax.swing.JTextField();
        btnSil = new javax.swing.JButton();
        btnGeri = new javax.swing.JButton();
        PanelKitapDegistir = new javax.swing.JPanel();
        lblDegisim = new javax.swing.JLabel();
        lblIsbnDegisim = new javax.swing.JLabel();
        lblyeniKitap = new javax.swing.JLabel();
        txtIsbnNoDegisim = new javax.swing.JTextField();
        txtYeniKitapIsmi = new javax.swing.JTextField();
        btnDegistir = new javax.swing.JButton();
        btnGeriDegistir = new javax.swing.JButton();
        txtDegisimKitap = new javax.swing.JTextField();
        lblDegisimKitap = new javax.swing.JLabel();
        PanelKitapSorgu = new javax.swing.JPanel();
        lblKitapSorgulama = new javax.swing.JLabel();
        lblIsbnSorgu = new javax.swing.JLabel();
        txtIsbnSorgu = new javax.swing.JTextField();
        btnGeriSorgu = new javax.swing.JButton();
        btnSorgula = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaSorguSonuc = new javax.swing.JTextArea();
        PanelKitapListele = new javax.swing.JPanel();
        lblMevcut = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listKitaplar = new javax.swing.JList<>();
        btnListele = new javax.swing.JButton();
        btnGeriListele = new javax.swing.JButton();
        PanelKitapYazarları = new javax.swing.JPanel();
        lblYazarlar = new javax.swing.JLabel();
        cmbYazarlar = new javax.swing.JComboBox<>();
        btnListeleYazarlar = new javax.swing.JButton();
        btnGeriYazarlar = new javax.swing.JButton();
        txtSeciliYazar = new javax.swing.JTextField();
        btnSeciliYazar = new javax.swing.JButton();
        PanelKitapDurum = new javax.swing.JPanel();
        lblKitapBilgisi = new javax.swing.JLabel();
        lblToplamKitapSayisi = new javax.swing.JLabel();
        txtToplamKitap = new javax.swing.JTextField();
        lblOrtalamaFiyat = new javax.swing.JLabel();
        txtOrtalamaFiyat = new javax.swing.JTextField();
        btnGosterBilgi = new javax.swing.JButton();
        btnOrtalama = new javax.swing.JButton();
        btnGeriKitap = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listYayınevleri = new javax.swing.JList<>();
        lblYayınevleri = new javax.swing.JLabel();
        btnYayınevleri = new javax.swing.JButton();
        PanelKitapFiyatlari = new javax.swing.JPanel();
        lblKitapToplam = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listToplam = new javax.swing.JList<>();
        btnListeleToplam = new javax.swing.JButton();
        btnGeriToplam = new javax.swing.JButton();
        txtToplamGoster = new javax.swing.JTextField();
        btnToplamFiyat = new javax.swing.JButton();
        PanelDosyadanOku = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDosyaOkuma = new javax.swing.JTable();
        btnKitapOku = new javax.swing.JButton();
        btnKullaniciOku = new javax.swing.JButton();
        btnGeriOku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        tblKitap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblKitap);

        btnKitapEkle.setText("Kitap Ekle");
        btnKitapEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapEkleActionPerformed(evt);
            }
        });

        btnKitapSil.setText("Kitap Sil");
        btnKitapSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapSilActionPerformed(evt);
            }
        });

        btnKitapDegistir.setText("Kitap Degistir");
        btnKitapDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapDegistirActionPerformed(evt);
            }
        });

        btnKitapSorgu.setText("Kitap Sorgu");
        btnKitapSorgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapSorguActionPerformed(evt);
            }
        });

        btnDosyadanOku.setText("Kitabı Dosyadan Oku");
        btnDosyadanOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosyadanOkuActionPerformed(evt);
            }
        });

        btnKitapYazdir.setText("Kitabı Dosyaya Yazdır");
        btnKitapYazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapYazdirActionPerformed(evt);
            }
        });

        btnKullaniciYazdir.setText("Kullanıcıyı Dosyaya Yazdır");
        btnKullaniciYazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciYazdirActionPerformed(evt);
            }
        });

        btnKitaplar.setText("Kitaplar");
        btnKitaplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitaplarActionPerformed(evt);
            }
        });

        btnKitapYazarlari.setText("Kitap Yazarları");
        btnKitapYazarlari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapYazarlariActionPerformed(evt);
            }
        });

        btnKitapDurum.setText("Kitap Durum");
        btnKitapDurum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapDurumActionPerformed(evt);
            }
        });

        btnKitapFiyatlari.setText("Kitap Fiyatları");
        btnKitapFiyatlari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapFiyatlariActionPerformed(evt);
            }
        });

        btnKullaniciDegistir.setText("Kullanıcı Degistir");
        btnKullaniciDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciDegistirActionPerformed(evt);
            }
        });

        jButton1.setText("Yenile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelYayinTakipLayout = new javax.swing.GroupLayout(PanelYayinTakip);
        PanelYayinTakip.setLayout(PanelYayinTakipLayout);
        PanelYayinTakipLayout.setHorizontalGroup(
            PanelYayinTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelYayinTakipLayout.createSequentialGroup()
                .addGroup(PanelYayinTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelYayinTakipLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelYayinTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnKitapDurum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKitapYazarlari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(btnKitaplar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKitapFiyatlari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelYayinTakipLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelYayinTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelYayinTakipLayout.createSequentialGroup()
                        .addComponent(btnKitapEkle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKitapSil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnKitapDegistir)
                        .addGap(102, 102, 102)
                        .addComponent(btnKitapSorgu))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelYayinTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKullaniciYazdir, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(btnKitapYazdir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDosyadanOku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKullaniciDegistir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelYayinTakipLayout.setVerticalGroup(
            PanelYayinTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelYayinTakipLayout.createSequentialGroup()
                .addGroup(PanelYayinTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelYayinTakipLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelYayinTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelYayinTakipLayout.createSequentialGroup()
                                .addComponent(btnKitaplar)
                                .addGap(50, 50, 50)
                                .addComponent(btnKitapYazarlari)
                                .addGap(38, 38, 38)
                                .addComponent(btnKitapDurum)
                                .addGap(59, 59, 59)
                                .addComponent(btnKitapFiyatlari))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelYayinTakipLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnKitapYazdir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKullaniciYazdir)
                        .addGap(37, 37, 37)
                        .addComponent(btnDosyadanOku)
                        .addGap(43, 43, 43)
                        .addComponent(btnKullaniciDegistir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelYayinTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKitapEkle)
                    .addComponent(btnKitapSil)
                    .addComponent(btnKitapSorgu)
                    .addComponent(btnKitapDegistir)
                    .addComponent(jButton1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(PanelYayinTakip, "card2");

        PanelKitapSil.setToolTipText("");

        lblIsbnNoBilgi.setText("ISBN Numarası Giriniz");

        lblIsbn.setText("Isbn No :");

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnGeri.setText("Geri");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKitapSilLayout = new javax.swing.GroupLayout(PanelKitapSil);
        PanelKitapSil.setLayout(PanelKitapSilLayout);
        PanelKitapSilLayout.setHorizontalGroup(
            PanelKitapSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapSilLayout.createSequentialGroup()
                .addGroup(PanelKitapSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKitapSilLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblIsbn)
                        .addGap(31, 31, 31)
                        .addGroup(PanelKitapSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIsbnNoBilgi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIsbnSil)))
                    .addGroup(PanelKitapSilLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnSil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGeri)))
                .addContainerGap(844, Short.MAX_VALUE))
        );
        PanelKitapSilLayout.setVerticalGroup(
            PanelKitapSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapSilLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblIsbnNoBilgi)
                .addGap(18, 18, 18)
                .addGroup(PanelKitapSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbn)
                    .addComponent(txtIsbnSil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelKitapSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSil)
                    .addComponent(btnGeri))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        getContentPane().add(PanelKitapSil, "card3");

        lblDegisim.setText("Degistirmek İstediğiniz Bilgileri Giriniz");

        lblIsbnDegisim.setText("Isbn Numarası :");

        lblyeniKitap.setText("Yeni Kitap İsmi :");

        btnDegistir.setText("Degistir");
        btnDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDegistirActionPerformed(evt);
            }
        });

        btnGeriDegistir.setText("Geri");
        btnGeriDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriDegistirActionPerformed(evt);
            }
        });

        lblDegisimKitap.setText("Degistirilecek Kitap :");

        javax.swing.GroupLayout PanelKitapDegistirLayout = new javax.swing.GroupLayout(PanelKitapDegistir);
        PanelKitapDegistir.setLayout(PanelKitapDegistirLayout);
        PanelKitapDegistirLayout.setHorizontalGroup(
            PanelKitapDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapDegistirLayout.createSequentialGroup()
                .addGroup(PanelKitapDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKitapDegistirLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(PanelKitapDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKitapDegistirLayout.createSequentialGroup()
                                .addComponent(btnDegistir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGeriDegistir))
                            .addGroup(PanelKitapDegistirLayout.createSequentialGroup()
                                .addComponent(lblyeniKitap)
                                .addGap(18, 18, 18)
                                .addComponent(txtYeniKitapIsmi))
                            .addGroup(PanelKitapDegistirLayout.createSequentialGroup()
                                .addComponent(lblIsbnDegisim)
                                .addGap(18, 18, 18)
                                .addComponent(txtIsbnNoDegisim, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addComponent(lblDegisimKitap)
                        .addGap(37, 37, 37)
                        .addComponent(txtDegisimKitap, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelKitapDegistirLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lblDegisim)))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        PanelKitapDegistirLayout.setVerticalGroup(
            PanelKitapDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapDegistirLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblDegisim)
                .addGap(18, 18, 18)
                .addGroup(PanelKitapDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbnDegisim)
                    .addComponent(txtIsbnNoDegisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelKitapDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblyeniKitap)
                    .addComponent(txtYeniKitapIsmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDegisimKitap)
                    .addComponent(txtDegisimKitap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelKitapDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGeriDegistir)
                    .addComponent(btnDegistir))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        getContentPane().add(PanelKitapDegistir, "card4");

        lblKitapSorgulama.setText("Kitap Sorgulama");

        lblIsbnSorgu.setText("Isbn No :");

        btnGeriSorgu.setText("Geri");
        btnGeriSorgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriSorguActionPerformed(evt);
            }
        });

        btnSorgula.setText("Sorgula");
        btnSorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorgulaActionPerformed(evt);
            }
        });

        txtaSorguSonuc.setColumns(20);
        txtaSorguSonuc.setRows(5);
        jScrollPane2.setViewportView(txtaSorguSonuc);

        javax.swing.GroupLayout PanelKitapSorguLayout = new javax.swing.GroupLayout(PanelKitapSorgu);
        PanelKitapSorgu.setLayout(PanelKitapSorguLayout);
        PanelKitapSorguLayout.setHorizontalGroup(
            PanelKitapSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapSorguLayout.createSequentialGroup()
                .addGroup(PanelKitapSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKitapSorguLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblIsbnSorgu)
                        .addGap(27, 27, 27)
                        .addGroup(PanelKitapSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIsbnSorgu, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelKitapSorguLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblKitapSorgulama))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKitapSorguLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSorgula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGeriSorgu)))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        PanelKitapSorguLayout.setVerticalGroup(
            PanelKitapSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapSorguLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblKitapSorgulama)
                .addGap(18, 18, 18)
                .addGroup(PanelKitapSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbnSorgu)
                    .addComponent(txtIsbnSorgu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelKitapSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGeriSorgu)
                    .addComponent(btnSorgula))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKitapSorguLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(PanelKitapSorgu, "card5");

        lblMevcut.setText("Sistemde Mevcut Olan Kitaplar");

        jScrollPane3.setViewportView(listKitaplar);

        btnListele.setText("Listele");
        btnListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleActionPerformed(evt);
            }
        });

        btnGeriListele.setText("Geri");
        btnGeriListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriListeleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKitapListeleLayout = new javax.swing.GroupLayout(PanelKitapListele);
        PanelKitapListele.setLayout(PanelKitapListeleLayout);
        PanelKitapListeleLayout.setHorizontalGroup(
            PanelKitapListeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapListeleLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelKitapListeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGeriListele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListele, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelKitapListeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMevcut)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(474, Short.MAX_VALUE))
        );
        PanelKitapListeleLayout.setVerticalGroup(
            PanelKitapListeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapListeleLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblMevcut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelKitapListeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelKitapListeleLayout.createSequentialGroup()
                        .addComponent(btnListele)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGeriListele)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(PanelKitapListele, "card6");

        lblYazarlar.setText("Kitabı Bulunan Yazarlar");

        btnListeleYazarlar.setText("Listele");
        btnListeleYazarlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleYazarlarActionPerformed(evt);
            }
        });

        btnGeriYazarlar.setText("Geri");
        btnGeriYazarlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriYazarlarActionPerformed(evt);
            }
        });

        btnSeciliYazar.setText("Secili Yazari Goster");
        btnSeciliYazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeciliYazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKitapYazarlarıLayout = new javax.swing.GroupLayout(PanelKitapYazarları);
        PanelKitapYazarları.setLayout(PanelKitapYazarlarıLayout);
        PanelKitapYazarlarıLayout.setHorizontalGroup(
            PanelKitapYazarlarıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapYazarlarıLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(PanelKitapYazarlarıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelKitapYazarlarıLayout.createSequentialGroup()
                        .addComponent(btnListeleYazarlar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGeriYazarlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblYazarlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbYazarlar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120)
                .addGroup(PanelKitapYazarlarıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSeciliYazar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeciliYazar))
                .addContainerGap(564, Short.MAX_VALUE))
        );
        PanelKitapYazarlarıLayout.setVerticalGroup(
            PanelKitapYazarlarıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapYazarlarıLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblYazarlar)
                .addGap(34, 34, 34)
                .addGroup(PanelKitapYazarlarıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbYazarlar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeciliYazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelKitapYazarlarıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListeleYazarlar)
                    .addComponent(btnGeriYazarlar)
                    .addComponent(btnSeciliYazar))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        getContentPane().add(PanelKitapYazarları, "card7");

        lblKitapBilgisi.setText("Kitap Bilgisi ");

        lblToplamKitapSayisi.setText("Toplam Kitap Sayısı :");

        lblOrtalamaFiyat.setText("Ortalama Fiyat :");

        btnGosterBilgi.setText("Goster");
        btnGosterBilgi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGosterBilgiActionPerformed(evt);
            }
        });

        btnOrtalama.setText("Ortalama");
        btnOrtalama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrtalamaActionPerformed(evt);
            }
        });

        btnGeriKitap.setText("Geri");
        btnGeriKitap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriKitapActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(listYayınevleri);

        lblYayınevleri.setText("Yayınevleri :");

        btnYayınevleri.setText("Yayınevleri");
        btnYayınevleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYayınevleriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKitapDurumLayout = new javax.swing.GroupLayout(PanelKitapDurum);
        PanelKitapDurum.setLayout(PanelKitapDurumLayout);
        PanelKitapDurumLayout.setHorizontalGroup(
            PanelKitapDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapDurumLayout.createSequentialGroup()
                .addGroup(PanelKitapDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKitapDurumLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblKitapBilgisi))
                    .addGroup(PanelKitapDurumLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelKitapDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblToplamKitapSayisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOrtalamaFiyat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblYayınevleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(PanelKitapDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtToplamKitap)
                            .addComponent(txtOrtalamaFiyat)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelKitapDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGeriKitap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOrtalama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGosterBilgi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnYayınevleri))))
                .addContainerGap())
        );
        PanelKitapDurumLayout.setVerticalGroup(
            PanelKitapDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKitapDurumLayout.createSequentialGroup()
                .addGroup(PanelKitapDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelKitapDurumLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelKitapDurumLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblKitapBilgisi)
                        .addGap(32, 32, 32)
                        .addGroup(PanelKitapDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblToplamKitapSayisi)
                            .addComponent(txtToplamKitap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGosterBilgi))
                        .addGap(14, 14, 14)
                        .addGroup(PanelKitapDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrtalamaFiyat)
                            .addComponent(txtOrtalamaFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOrtalama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(PanelKitapDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKitapDurumLayout.createSequentialGroup()
                                .addComponent(btnYayınevleri)
                                .addGap(43, 43, 43)
                                .addComponent(btnGeriKitap))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKitapDurumLayout.createSequentialGroup()
                                .addComponent(lblYayınevleri)
                                .addGap(64, 64, 64)))))
                .addGap(21, 21, 21))
        );

        getContentPane().add(PanelKitapDurum, "card8");

        lblKitapToplam.setText("Kitapların Toplam Fiyatı ");

        jScrollPane5.setViewportView(listToplam);

        btnListeleToplam.setText("Listele");
        btnListeleToplam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleToplamActionPerformed(evt);
            }
        });

        btnGeriToplam.setText("Geri");
        btnGeriToplam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriToplamActionPerformed(evt);
            }
        });

        btnToplamFiyat.setText("Toplam Fiyat");
        btnToplamFiyat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToplamFiyatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKitapFiyatlariLayout = new javax.swing.GroupLayout(PanelKitapFiyatlari);
        PanelKitapFiyatlari.setLayout(PanelKitapFiyatlariLayout);
        PanelKitapFiyatlariLayout.setHorizontalGroup(
            PanelKitapFiyatlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapFiyatlariLayout.createSequentialGroup()
                .addGroup(PanelKitapFiyatlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKitapFiyatlariLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lblKitapToplam))
                    .addGroup(PanelKitapFiyatlariLayout.createSequentialGroup()
                        .addGroup(PanelKitapFiyatlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelKitapFiyatlariLayout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(btnListeleToplam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGeriToplam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelKitapFiyatlariLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(PanelKitapFiyatlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtToplamGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnToplamFiyat))))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        PanelKitapFiyatlariLayout.setVerticalGroup(
            PanelKitapFiyatlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKitapFiyatlariLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblKitapToplam)
                .addGap(18, 18, 18)
                .addGroup(PanelKitapFiyatlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKitapFiyatlariLayout.createSequentialGroup()
                        .addComponent(txtToplamGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnToplamFiyat))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelKitapFiyatlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListeleToplam)
                    .addComponent(btnGeriToplam))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(PanelKitapFiyatlari, "card9");

        tblDosyaOkuma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tblDosyaOkuma);

        btnKitapOku.setText("Kitap Oku");
        btnKitapOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapOkuActionPerformed(evt);
            }
        });

        btnKullaniciOku.setText("Kullanıcı Oku");
        btnKullaniciOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciOkuActionPerformed(evt);
            }
        });

        btnGeriOku.setText("Geri");
        btnGeriOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriOkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDosyadanOkuLayout = new javax.swing.GroupLayout(PanelDosyadanOku);
        PanelDosyadanOku.setLayout(PanelDosyadanOkuLayout);
        PanelDosyadanOkuLayout.setHorizontalGroup(
            PanelDosyadanOkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDosyadanOkuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelDosyadanOkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKullaniciOku)
                    .addComponent(btnKitapOku, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeriOku, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        PanelDosyadanOkuLayout.setVerticalGroup(
            PanelDosyadanOkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDosyadanOkuLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(PanelDosyadanOkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelDosyadanOkuLayout.createSequentialGroup()
                        .addComponent(btnKitapOku)
                        .addGap(99, 99, 99)
                        .addComponent(btnKullaniciOku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGeriOku)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDosyadanOkuLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(PanelDosyadanOku, "card11");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKitapEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapEkleActionPerformed
        // TODO add your handling code here:
        KitapEkleme ke = new KitapEkleme();
        ke.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKitapEkleActionPerformed

    private void btnKitapSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapSilActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(false);
        PanelKitapSil.setVisible(true);
    }//GEN-LAST:event_btnKitapSilActionPerformed

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(true);
        PanelKitapSil.setVisible(false);
        txtIsbnSil.setText("");
    }//GEN-LAST:event_btnGeriActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("delete from Kitaplar k WHERE k.isbn = :isbn");
        Query q1 = em.createQuery("select k1 from Kitaplar k1");
        q.setParameter("isbn", Integer.valueOf(txtIsbnSil.getText()));
        
        
        List<Kitaplar> kitaplar = q1.getResultList();
        
        for (Kitaplar k1 : kitaplar) {
            
            if(!txtIsbnSil.getText().equals(String.valueOf(k1.getIsbn()))){
                JOptionPane.showMessageDialog(this, "Girdiğiniz ISBN Numarali Kitap Bulunmamaktadır.");
            }
        }
        em.getTransaction().begin();
        q.executeUpdate();
        
        em.getTransaction().commit();
        em.close();
        emf.close();
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnKitapDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapDegistirActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(false);
        PanelKitapDegistir.setVisible(true);
    }//GEN-LAST:event_btnKitapDegistirActionPerformed

    private void btnDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDegistirActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("update Kitaplar k set k.kitapismi=:KITAPISMI where k.isbn=:ISBN");
        Query q1 = em.createQuery("select k from Kitaplar k");
               
        q.setParameter("KITAPISMI", txtYeniKitapIsmi.getText());
        q.setParameter("ISBN", Integer.parseInt(txtIsbnNoDegisim.getText()));
        
        
        List<Kitaplar> kitaplar = q1.getResultList();
        
        
        for (Kitaplar k1 : kitaplar) {
            if(txtIsbnNoDegisim.getText().equals(String.valueOf(k1.getIsbn()))){
                txtDegisimKitap.setText(k1.getKitapismi());
            }
        }
        em.getTransaction().begin();
        q.executeUpdate();

        em.getTransaction().commit();
        em.close();
        emf.close();
    }//GEN-LAST:event_btnDegistirActionPerformed

    private void btnGeriDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriDegistirActionPerformed
        // TODO add your handling code here:
        PanelKitapDegistir.setVisible(false);
        PanelYayinTakip.setVisible(true);
        txtIsbnNoDegisim.setText("");
        txtYeniKitapIsmi.setText("");
        txtDegisimKitap.setText("");
    }//GEN-LAST:event_btnGeriDegistirActionPerformed

    private void btnKitapSorguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapSorguActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(false);
        PanelKitapSorgu.setVisible(true);
    }//GEN-LAST:event_btnKitapSorguActionPerformed

    private void btnGeriSorguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriSorguActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(true);
        PanelKitapSorgu.setVisible(false);
    }//GEN-LAST:event_btnGeriSorguActionPerformed

    private void btnSorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorgulaActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kitaplar k where k.isbn=:ISBNO");

        q.setParameter("ISBNO", Integer.parseInt(txtIsbnSorgu.getText()));
        List<Kitaplar> kitaplar = q.getResultList();

        for (Kitaplar k : kitaplar) {
            txtaSorguSonuc.setText("Kitap İsmi : " + k.getKitapismi() + "\n"
                    + "Basım Yılı : " + k.getBasimyili() + "\n"
                    + "Kitap Fiyatı : " + k.getFiyat() + " TL " + "\n"
                    + "Yayınevi : " + k.getYayinevi() + "\n"
                    + "Yazarı :  " + k.getYazar() + "\n"
                    + "Sayfa Sayısı : " + k.getSayfasayisi() + "\n");
        }
        em.close();
        emf.close();


    }//GEN-LAST:event_btnSorgulaActionPerformed

    private void btnKitaplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitaplarActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(false);
        PanelKitapListele.setVisible(true);
    }//GEN-LAST:event_btnKitaplarActionPerformed

    private void btnListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kitaplar k");
        List<Kitaplar> kitaplar = q.getResultList();

        for (Kitaplar k : kitaplar) {
            dlm.addElement(k.getYayinevi() + " Yayınevinde " + k.getKitapismi() + " kitabı bulunmaktadır.");

        }

        em.close();
        emf.close();
    }//GEN-LAST:event_btnListeleActionPerformed

    private void btnKitapYazarlariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapYazarlariActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(false);
        PanelKitapYazarları.setVisible(true);
    }//GEN-LAST:event_btnKitapYazarlariActionPerformed

    private void btnGeriYazarlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriYazarlarActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(true);
        PanelKitapYazarları.setVisible(false);
        cmbYazarlar.removeAllItems();
        txtSeciliYazar.setText("");
    }//GEN-LAST:event_btnGeriYazarlarActionPerformed

    private void btnListeleYazarlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleYazarlarActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kitaplar k");
        List<Kitaplar> kitaplar = q.getResultList();

        for (Kitaplar k : kitaplar) {
            cmbYazarlar.addItem(k.getYazar());

        }
        
        

        em.close();
        emf.close();
    }//GEN-LAST:event_btnListeleYazarlarActionPerformed

    private void btnSeciliYazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeciliYazarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i <= cmbYazarlar.getSelectedIndex(); i++) {
            txtSeciliYazar.setText(cmbYazarlar.getItemAt(i));
        }
    }//GEN-LAST:event_btnSeciliYazarActionPerformed

    private void btnKitapDurumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapDurumActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(false);
        PanelKitapDurum.setVisible(true);
    }//GEN-LAST:event_btnKitapDurumActionPerformed

    private void btnGosterBilgiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGosterBilgiActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kitaplar k");
        List<Kitaplar> kitaplar = q.getResultList();
     
        
        int toplamkitap = dtm.getRowCount();
        
        txtToplamKitap.setText(" Sistemde " + String.valueOf(toplamkitap) + " adet kitap yer almaktadır.");
        
        em.close();
        emf.close();
    }//GEN-LAST:event_btnGosterBilgiActionPerformed

    private void btnOrtalamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrtalamaActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kitaplar k");
        List<Kitaplar> kitaplar = q.getResultList();
        
        int toplamkitap = 0;
        double ortalamaFiyat = 0;
        int toplamTutar = 0;
        
        toplamkitap = dtm.getRowCount();
        for (Kitaplar k : kitaplar) {
            toplamTutar += k.getFiyat();
            ortalamaFiyat = (double) toplamTutar / (double) toplamkitap;
            
        }
        txtOrtalamaFiyat.setText("Kitapların ortalama fiyatı = " + String.valueOf(ortalamaFiyat) + " TL'dir.");
        
        em.close();
        emf.close();
    }//GEN-LAST:event_btnOrtalamaActionPerformed

    private void btnGeriKitapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriKitapActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(true);
        PanelKitapDurum.setVisible(false);
        txtOrtalamaFiyat.setText("");
        txtToplamKitap.setText("");
        dlm2.removeAllElements();
        
    }//GEN-LAST:event_btnGeriKitapActionPerformed

    private void btnYayınevleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYayınevleriActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kitaplar k");
        List<Kitaplar> kitaplar = q.getResultList();
        
        for (Kitaplar k : kitaplar) {
            dlm2.addElement(k.getKitapismi() + " kitabı " + k.getYayinevi() + " yayınevinden çıkmaktadır. " );
            
        }
        
        em.close();
        emf.close();
    }//GEN-LAST:event_btnYayınevleriActionPerformed

    private void btnKitapFiyatlariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapFiyatlariActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(false);
        PanelKitapFiyatlari.setVisible(true);
    }//GEN-LAST:event_btnKitapFiyatlariActionPerformed

    private void btnGeriToplamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriToplamActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(true);
        PanelKitapFiyatlari.setVisible(false);
        dlm3.removeAllElements();
        txtToplamGoster.setText("");
    }//GEN-LAST:event_btnGeriToplamActionPerformed

    private void btnListeleToplamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleToplamActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kitaplar k");
        List<Kitaplar> kitaplar = q.getResultList();
        
        for (Kitaplar k : kitaplar) {
            dlm3.addElement(k.getKitapismi() + " kitabının ucreti " + k.getFiyat()+  " TL'dir. ");
            
        }
        
        em.close();
        emf.close();
    }//GEN-LAST:event_btnListeleToplamActionPerformed

    private void btnToplamFiyatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToplamFiyatActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kitaplar k");
        List<Kitaplar> kitaplar = q.getResultList();
        
        int toplamFiyat =0;
        
        for (Kitaplar k : kitaplar) {
            toplamFiyat+=k.getFiyat();
        }
        txtToplamGoster.setText("Mevcut kitapların toplam fiyatı = " + String.valueOf(toplamFiyat) +" TL ");
    }//GEN-LAST:event_btnToplamFiyatActionPerformed

    private void btnKullaniciDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciDegistirActionPerformed
        // TODO add your handling code here:
        KullaniciGiris kg = new KullaniciGiris();
        kg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnKullaniciDegistirActionPerformed

    private void btnKitapYazdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapYazdirActionPerformed
        // TODO add your handling code here:
         EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kitaplar k");
        
        List<Kitaplar> kitaplar = q.getResultList();
        String dosya ="c:\\dosyalar\\kitaplar.txt";
        
        try {
            BufferedWriter f = new BufferedWriter(new FileWriter(dosya));
            for (Kitaplar k : kitaplar) {
                f.write(k.getIsbn() + " ISBN numaralı " + k.getKitapismi()+ " kitabı " +k.getBasimyili() +" yılında yazılmıştır ve "
                        +k.getYayinevi()+" yayınevinden çıkmaktadır. "+" Yazarı "+k.getYazar()
                        +" olan kitabın fiyatı "+ k.getFiyat() +" TL 'dir." +" Kitap " +k.getSayfasayisi() +" sayfadır."+ "\n");
                        
            }
            f.close();
            em.close();
            emf.close();
            
        } catch (IOException ex) {
            Logger.getLogger(YayınTakip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKitapYazdirActionPerformed

    private void btnKullaniciYazdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciYazdirActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k1 from Kullanicilar k1");
       
        List<Kullanicilar> kullanicilar = q.getResultList();
        String dosya ="c:\\dosyalar\\kullanicilar.txt";
        
        try {
            BufferedWriter f = new BufferedWriter(new FileWriter(dosya));
            for (Kullanicilar k1 : kullanicilar) {
                f.write(k1.getTc()+" kimlik numaralı "+k1.getAdi()+ " " +k1.getSoyadi() +" personelinin kullanıcı adı  " 
                        +k1.getKullaniciadi()+ " ve şifresi "+k1.getSifre()+ "'dir."+" Kullanicinin Mail Adresi " +k1.getMail()+ " \n ");
            }
            
            f.close();
            em.close();
            emf.close();
            
        } catch (IOException ex) {
            Logger.getLogger(YayınTakip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKullaniciYazdirActionPerformed

    private void btnDosyadanOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosyadanOkuActionPerformed
        // TODO add your handling code here:
        PanelYayinTakip.setVisible(false);
        PanelDosyadanOku.setVisible(true);
    }//GEN-LAST:event_btnDosyadanOkuActionPerformed

    private void btnGeriOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriOkuActionPerformed
        // TODO add your handling code here:
         PanelYayinTakip.setVisible(true);
        PanelDosyadanOku.setVisible(false);
    }//GEN-LAST:event_btnGeriOkuActionPerformed

    private void btnKitapOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapOkuActionPerformed
        // TODO add your handling code here:
        dtm2.setColumnIdentifiers(new String[]{"Kitap Bilgileri"});
       
        String dosya = "c:\\dosyalar\\kitaplar.txt";
        BufferedReader reader=null;
        try {
             
            reader = new BufferedReader(new FileReader(dosya));
            String satir = reader.readLine();
            
            while(satir!=null){
                dtm2.addRow(new Object[]{satir});
                satir=reader.readLine();
            }
        } catch (FileNotFoundException ex) {
                Logger.getLogger(YayınTakip.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(YayınTakip.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try{
                reader.close();
            }catch (IOException ex) {
                Logger.getLogger(YayınTakip.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnKitapOkuActionPerformed

    private void btnKullaniciOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciOkuActionPerformed
        // TODO add your handling code here:
         dtm2.setColumnIdentifiers(new String[]{"Kullanıcı Bilgileri"});
       
        String dosya = "c:\\dosyalar\\kullanicilar.txt";
        BufferedReader reader=null;
        try {
             
            reader = new BufferedReader(new FileReader(dosya));
            String satir = reader.readLine();
            
            while(satir!=null){
                dtm2.addRow(new Object[]{satir});
                satir=reader.readLine();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(YayınTakip.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(YayınTakip.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try{
                reader.close();
            }catch (IOException ex) {
                Logger.getLogger(YayınTakip.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnKullaniciOkuActionPerformed

    private void btnGeriListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriListeleActionPerformed
        // TODO add your handling code here:
        PanelKitapListele.setVisible(false);
        PanelYayinTakip.setVisible(true);
        dlm.removeAllElements();
    }//GEN-LAST:event_btnGeriListeleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dtm.setColumnIdentifiers(new String[]{"ISBN", "KITAPISMI", "BASIMYILI", "SAYFASAYISI", "FIYAT", "YAYINEVI", "YAZAR"});
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Tugfe_Ivecek_1621231018_BPII_Odev2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kitaplar k ");
        List<Kitaplar> kitaplar = q.getResultList();
        dtm.setRowCount(0);
        for (Kitaplar k : kitaplar) {
            dtm.addRow(new Object[]{k.getIsbn(), k.getKitapismi(), k.getBasimyili(),
                k.getSayfasayisi(), k.getFiyat(), k.getYayinevi(), k.getYazar()});
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YayınTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YayınTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YayınTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YayınTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YayınTakip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDosyadanOku;
    private javax.swing.JPanel PanelKitapDegistir;
    private javax.swing.JPanel PanelKitapDurum;
    private javax.swing.JPanel PanelKitapFiyatlari;
    private javax.swing.JPanel PanelKitapListele;
    private javax.swing.JPanel PanelKitapSil;
    private javax.swing.JPanel PanelKitapSorgu;
    private javax.swing.JPanel PanelKitapYazarları;
    private javax.swing.JPanel PanelYayinTakip;
    private javax.swing.JButton btnDegistir;
    private javax.swing.JButton btnDosyadanOku;
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnGeriDegistir;
    private javax.swing.JButton btnGeriKitap;
    private javax.swing.JButton btnGeriListele;
    private javax.swing.JButton btnGeriOku;
    private javax.swing.JButton btnGeriSorgu;
    private javax.swing.JButton btnGeriToplam;
    private javax.swing.JButton btnGeriYazarlar;
    private javax.swing.JButton btnGosterBilgi;
    private javax.swing.JButton btnKitapDegistir;
    private javax.swing.JButton btnKitapDurum;
    private javax.swing.JButton btnKitapEkle;
    private javax.swing.JButton btnKitapFiyatlari;
    private javax.swing.JButton btnKitapOku;
    private javax.swing.JButton btnKitapSil;
    private javax.swing.JButton btnKitapSorgu;
    private javax.swing.JButton btnKitapYazarlari;
    private javax.swing.JButton btnKitapYazdir;
    private javax.swing.JButton btnKitaplar;
    private javax.swing.JButton btnKullaniciDegistir;
    private javax.swing.JButton btnKullaniciOku;
    private javax.swing.JButton btnKullaniciYazdir;
    private javax.swing.JButton btnListele;
    private javax.swing.JButton btnListeleToplam;
    private javax.swing.JButton btnListeleYazarlar;
    private javax.swing.JButton btnOrtalama;
    private javax.swing.JButton btnSeciliYazar;
    private javax.swing.JButton btnSil;
    private javax.swing.JButton btnSorgula;
    private javax.swing.JButton btnToplamFiyat;
    private javax.swing.JButton btnYayınevleri;
    private javax.swing.JComboBox<String> cmbYazarlar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblDegisim;
    private javax.swing.JLabel lblDegisimKitap;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblIsbnDegisim;
    private javax.swing.JLabel lblIsbnNoBilgi;
    private javax.swing.JLabel lblIsbnSorgu;
    private javax.swing.JLabel lblKitapBilgisi;
    private javax.swing.JLabel lblKitapSorgulama;
    private javax.swing.JLabel lblKitapToplam;
    private javax.swing.JLabel lblMevcut;
    private javax.swing.JLabel lblOrtalamaFiyat;
    private javax.swing.JLabel lblToplamKitapSayisi;
    private javax.swing.JLabel lblYayınevleri;
    private javax.swing.JLabel lblYazarlar;
    private javax.swing.JLabel lblyeniKitap;
    private javax.swing.JList<String> listKitaplar;
    private javax.swing.JList<String> listToplam;
    private javax.swing.JList<String> listYayınevleri;
    private javax.swing.JTable tblDosyaOkuma;
    private javax.swing.JTable tblKitap;
    private javax.swing.JTextField txtDegisimKitap;
    private javax.swing.JTextField txtIsbnNoDegisim;
    private javax.swing.JTextField txtIsbnSil;
    private javax.swing.JTextField txtIsbnSorgu;
    private javax.swing.JTextField txtOrtalamaFiyat;
    private javax.swing.JTextField txtSeciliYazar;
    private javax.swing.JTextField txtToplamGoster;
    private javax.swing.JTextField txtToplamKitap;
    private javax.swing.JTextField txtYeniKitapIsmi;
    private javax.swing.JTextArea txtaSorguSonuc;
    // End of variables declaration//GEN-END:variables
}
